on:
  push:
    branches: main
#  schedule:
#    - cron: '0 1,7,13,19 * * *'

name: Post

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      BLUESKY_APP_USER: ${{ secrets.BLUESKY_APP_USER }}
      BLUESKY_APP_PASS: ${{ secrets.BLUESKY_APP_PASS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::here
            github::christopherkenny/bskyr

      - run: Rscript 'post.R'
